In [1]:
  import pandas as pd

# Create sample dataset

data = {
    "StudentID":[101,102,103,104,105,106,107,108],
    "Name":["Aman","Priya","Rahul","Neha","Mohit","Sneha","Arjun","Riya"],
    "Gender":["Male","Female","Male","Female","Male","Female","Male","Female"],
    "Department":["CSE","IT","ECE","CSE","ME","CSE","Civil","IT"],
    "Year":["First","Second","Third","Fourth","Second","Third","First","Fourth"],
    "Hostel":["Yes","No","Yes","No","Yes","Yes","No","Yes"],
    "Age":[18,19,20,21,19,20,18,21],
    "Semester":[1,3,5,7,3,5,1,7],
    "CGPA":[8.2,8.75,7.9,9.1,7.5,8.95,7.85,9.35],
    "Attendance":[92.5,88.0,81.5,95.2,78.4,90.3,83.6,97.1],
    "FamilyIncome":[450000,550000,600000,720000,380000,650000,300000,850000],
    "Placed":["No","No","Yes","Yes","No","Yes","No","Yes"]
}

df = pd.DataFrame(data)

print(df)

# Save as CSV
df.to_csv("student_data.csv", index=False)

   StudentID   Name  Gender Department    Year Hostel  Age  Semester  CGPA  \
0        101   Aman    Male        CSE   First    Yes   18         1  8.20
1        102  Priya  Female         IT  Second     No   19         3  8.75
2        103  Rahul    Male        ECE   Third    Yes   20         5  7.90
3        104   Neha  Female        CSE  Fourth     No   21         7  9.10
4        105  Mohit    Male         ME  Second    Yes   19         3  7.50
5        106  Sneha  Female        CSE   Third    Yes   20         5  8.95
6        107  Arjun    Male      Civil   First     No   18         1  7.85
7        108   Riya  Female         IT  Fourth    Yes   21         7  9.35

   Attendance  FamilyIncome Placed
0        92.5        450000     No
1        88.0        550000     No
2        81.5        600000    Yes
3        95.2        720000    Yes
4        78.4        380000     No
5        90.3        650000    Yes
6        83.6        300000     No
7        97.1        850000    Yes

In [2]:
df.head()

,StudentID,Name,Gender,Department,Year,Hostel,Age,Semester,CGPA,Attendance,FamilyIncome,Placed
0,101,Aman,Male,CSE,First,Yes,18,1,8.20,92.5,450000,No
1,102,Priya,Female,IT,Second,No,19,3,8.75,88.0,550000,No
2,103,Rahul,Male,ECE,Third,Yes,20,5,7.90,81.5,600000,Yes
3,104,Neha,Female,CSE,Fourth,No,21,7,9.10,95.2,720000,Yes
4,105,Mohit,Male,ME,Second,Yes,19,3,7.50,78.4,380000,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   StudentID     8 non-null      int64
 1   Name          8 non-null      object
 2   Gender        8 non-null      object
 3   Department    8 non-null      object
 4   Year          8 non-null      object
 5   Hostel        8 non-null      object
 6   Age           8 non-null      int64
 7   Semester      8 non-null      int64
 8   CGPA          8 non-null      float64
 9   Attendance    8 non-null      float64
 10  FamilyIncome  8 non-null      int64
 11  Placed        8 non-null      object
dtypes: float64(2), int64(4), object(6)
memory usage: 896.0+ bytes

In [4]:
df.shape

(8, 12)

In [5]:
df.describe()

       StudentID        Age  Semester      CGPA  Attendance   FamilyIncome
count    8.00000   8.000000  8.000000  8.000000    8.000000       8.000000
mean   104.50000  19.500000  4.000000  8.450000   88.325000  562500.000000
std      2.44949   1.195229  2.390457  0.676123    6.688102  181875.153412
min    101.00000  18.000000  1.000000  7.500000   78.400000  300000.000000
25%    102.75000  18.750000  2.500000  7.887500   83.075000  432500.000000
50%    104.50000  19.500000  4.000000  8.475000   89.150000  575000.000000
75%    106.25000  20.250000  5.500000  8.987500   93.175000  667500.000000
max    108.00000  21.000000  7.000000  9.350000   97.100000  850000.000000

In [6]:
df.columns

Index(['StudentID', 'Name', 'Gender', 'Department', 'Year', 'Hostel', 'Age',
       'Semester', 'CGPA', 'Attendance', 'FamilyIncome', 'Placed'],
      dtype='object')

In [7]:
df.dtypes

StudentID         int64
Name             object
Gender           object
Department       object
Year             object
Hostel           object
Age               int64
Semester          int64
CGPA            float64
Attendance      float64
FamilyIncome      int64
Placed           object
dtype: object

In [8]:
df.isnull().sum()

StudentID       0
Name            0
Gender          0
Department      0
Year            0
Hostel          0
Age             0
Semester        0
CGPA            0
Attendance      0
FamilyIncome    0
Placed          0
dtype: int64

In [9]:
print("Attribute Types\n")

print("StudentID      -> Numeric (Discrete)")
print("Name           -> Nominal")
print("Gender         -> Binary")
print("Department     -> Nominal")
print("Year           -> Ordinal")
print("Hostel         -> Binary")
print("Age            -> Numeric (Discrete)")
print("Semester       -> Numeric (Discrete)")
print("CGPA           -> Numeric (Continuous)")
print("Attendance     -> Numeric (Continuous)")
print("FamilyIncome   -> Numeric (Continuous)")
print("Placed         -> Binary")

Attribute Types

StudentID      -> Numeric (Discrete)
Name           -> Nominal
Gender         -> Binary
Department     -> Nominal
Year           -> Ordinal
Hostel         -> Binary
Age            -> Numeric (Discrete)
Semester       -> Numeric (Discrete)
CGPA           -> Numeric (Continuous)
Attendance     -> Numeric (Continuous)
FamilyIncome   -> Numeric (Continuous)
Placed         -> Binary